#!/usr/bin/env bash

DESCRIPTIONS_PATH=$(dirname "$(realpath $0)")/descriptions

mkdir -p $DESCRIPTIONS_PATH
cd $DESCRIPTIONS_PATH

git clone https://github.com/chvmp/mini-cheetah-gazebo-urdf
git clone https://github.com/chvmp/spotmicro_description
git clone https://github.com/chvmp/littledog_description
git clone https://github.com/chvmp/anymal_b_simple_description
git clone https://github.com/chvmp/anymal_c_simple_description
git clone https://github.com/chvmp/dkitty_description
git clone https://github.com/chvmp/opendog_description
git clone -b gazebo https://github.com/chvmp/spot_ros
git clone https://github.com/moribots/spot_mini_mini
git clone https://github.com/chvmp/unitree_ros
git clone https://github.com/aditya-shirwatkar/stochlite_description